version: '3.1'
services: 
   mongodb:
      image: mongo:4.4.29
      ports: 
        - 27017:27017
      environment: 
         MONGO_INITDB_ROOT_USERNAME: admin
         MONGO_INITDB_ROOT_PASSWORD: root

   express: 
      image: mongo-express
      ports: 
        - 8081:8081
      environment: 
         ME_CONFIG_MONGODB_ADMINUSERNAME: admin
         ME_CONFIG_MONGODB_ADMINPASSWORD: root
         ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on: 
         - "mongodb"
